name: terraform-ci

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8
      - name: Terraform fmt
        run: terraform -chdir=terraform/environments/dev fmt -check -recursive
      - name: Terraform init without backend
        run: terraform -chdir=terraform/environments/dev init -backend=false
      - name: Terraform validate
        run: terraform -chdir=terraform/environments/dev validate
